# Generated by Django 4.2.14 on 2024-08-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=50)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_title', models.CharField(max_length=200)),
                ('credit_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('stream', models.CharField(blank=True, max_length=100)),
                ('campus', models.CharField(blank=True, max_length=100)),
                ('lecturer', models.CharField(blank=True, max_length=200)),
                ('lecturer_title', models.CharField(blank=True, max_length=100)),
                ('lecturer_status', models.CharField(blank=True, max_length=100)),
                ('no_of_students', models.PositiveIntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
